apiVersion: v1
kind: Service
metadata:
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    tier: backend
  name: frontend-website-mr
  namespace: default
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.0.1.204
  clusterIPs:
  - 10.0.1.204
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31785
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: frontend-website-mr
    tier: backend
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 20.253.35.9
